//! Integration tests for [`kerf_cad::import_step`] driven by on-disk
//! fixture files. The fixture under `tests/fixtures/cube.step` was
//! generated by kerf's own `kerf_brep::write_step` for a 2×2×2 box, so
//! this exercises the full round-trip kerf-out → STEP file → kerf-in.

use std::fs;

use kerf_brep::measure::solid_volume;
use kerf_cad::import_step;

#[test]
fn cube_fixture_imports_to_volume_8() {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("fixtures")
        .join("cube.step");
    let text = fs::read_to_string(&path).expect("read fixture");
    let solid = import_step(&text).expect("import");
    let vol = solid_volume(&solid);
    assert!(
        (vol - 8.0).abs() < 1e-6,
        "imported cube volume = {vol}, expected 8.0"
    );
    assert_eq!(solid.vertex_count(), 8, "cube has 8 vertices");
}
